# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 925ca93f06d2a017ec3e363248fd09d3fad844e7e9785f95338a6101957141e1bd23cd95a5de212b35385a7ffb0190b024bdf2feb1c1c986583730b033e9b54c

test:
  secret_key_base: 5d4de266ac2b32e531ecc712c7f9e9268d0e78fb36e1bf0ecf521a2fa57fc9300f16bb7c3e12c6b233301565f088727d281aac549eca35d3eb2dee589c8be2d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
